### ISSUE TITLE
build时清理build文件夹与部署在github pages之间的冲突

### ISSUE THREAD

**Issue by mokizzz** [teadocs/teadocs#9]
`/build`文件夹下的内容可以轻松部署在gh page上，只需在该文件夹下添加一个名为_config.yml的文件，内容如下：

> theme: jekyll-theme-cayman

但是每次执行`teadocs build`指令后，该文件就会被清除，导致需要手动重新创建该文件。是否有什么办法在build时忽略该文件，或者有更好的办法部署到github page上？

**Comment by dkvirus** [comment]
建两个分支：develop 和 master

develop 分支放你的源代码，_config.yml 文件放在 develop 分支上，travis 监听你的 develop 分支有变化，执行 `teadoc build` 命令生成 build 目录，再将 build 目录复制到 mater 分支上。这一系列动作交给 travis 来做，不需要手动操作。

具体可以参考  [travis + github page](https://blog.dkvirus.top/%E5%BB%BA%E7%AB%99/Travis%20%E6%8C%81%E7%BB%AD%E9%9B%86%E6%88%90%E8%87%AA%E5%8A%A8%E5%8F%91%E5%B8%83%E5%8D%9A%E5%AE%A2%E6%96%87%E7%AB%A0/)

**Comment by mokizzz** [comment]
十分感谢！travis 非常有效。但是在自动 build 的过程中出现了问题

实际上，我采用了这样的方法：假设我的源代码仓库名为xxx，我将 build 生成的东西放在了另一仓库 xxx.github.io 中去。在使用 travis 时，参照 [travis + github page](https://blog.dkvirus.top/%E5%BB%BA%E7%AB%99/Travis%20%E6%8C%81%E7%BB%AD%E9%9B%86%E6%88%90%E8%87%AA%E5%8A%A8%E5%8F%91%E5%B8%83%E5%8D%9A%E5%AE%A2%E6%96%87%E7%AB%A0/) ，我的 .travis.yml 文件配置如下：

```
# 设置运行环境
language: node_js
node_js: stable

# 安装依赖包
install:
  - npm install -g teadocs

# 生成网页静态资源
script:
  - teadocs build

# 将静态资源推送到远程仓库某分支
after_script:
  # 复制_config.yml
  - cp _config.yml ./build
  # git options
  - cd ./build
  - git init
  - git config user.name "我的用户名"
  - git config user.email "我的邮箱"
  - git add .
  - git commit -m "update pages"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    # 设置监控分支
    - master
env:
  global:
    - GH_REF: github.com/xxx/xxx.github.io.git
```

travis CI 中 build 结果 [在这里](https://travis-ci.com/ffobook/ffobook/builds/121527273)。所有指令都执行成功了，并且成功部署。但是指令`teadocs build`返回了一个 "exit code 1"，导致 build 结果显示为 "fail"。具体 log 如下：

```
210$ teadocs build
211remove build dir.
212make build dir.
213copy static to build dir.
214>>> output: /home/travis/build/ffobook/ffobook/build/index.html
215>>> output: /home/travis/build/ffobook/ffobook/build/game/career/index.html
216>>> output: /home/travis/build/ffobook/ffobook/build/game/career/zs.html
217>>> output: /home/travis/build/ffobook/ffobook/build/game/career/jk.html
218>>> output: /home/travis/build/ffobook/ffobook/build/game/career/ck.html
219>>> output: /home/travis/build/ffobook/ffobook/build/game/career/ss.html
220>>> output: /home/travis/build/ffobook/ffobook/build/game/career/ys.html
221>>> output: /home/travis/build/ffobook/ffobook/build/game/equipment/index.html
222>>> output: /home/travis/build/ffobook/ffobook/build/game/pet/index.html
223>>> output: /home/travis/build/ffobook/ffobook/build/teadocs_error_pages/404.html
224wrtie data of the search: /home/travis/build/ffobook/ffobook/build/data.js
225 DONE  Compiled successfully.
226The command "teadocs build" exited with 1.
```

根据 [这里](http://nodejs.cn/api/process/process_exit_code.html) ， `process.exit([code])` 指令中 code 值为 0 时表示成功，为 1 时表示失败，所以 `teadocs build` 指令是以失败结束的。

我查看了 teadocs 源代码`/lib/build.js`，发现相关操作如下：

```javascript
        console.log(chalk.bgGreen(" DONE ") + " Compiled successfully.")
        if ( !this.options.dev ) {
            process.exit(1)
        }
```

代码中，在未设置 "this.options.dev" 的情况下以状态码 1 结束。我应该如何才能以状态码 0 来结束呢？
